<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countrylist = [
            [
                "id" => 1,
                "name" => "Afghanistan",
                "timezone" => "UTC+04:30",
                "flag" => "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 2,
                "name" => "Åland Islands",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ax.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 3,
                "name" => "Albania",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/al.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 4,
                "name" => "Algeria",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/dz.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 5,
                "name" => "American Samoa",
                "timezone" => "UTC-11:00",
                "flag" => "https://flagcdn.com/w320/as.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 6,
                "name" => "Andorra",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ad.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 7,
                "name" => "Angola",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ao.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 8,
                "name" => "Anguilla",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/ai.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 9,
                "name" => "Antarctica",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/aq.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 10,
                "name" => "Antigua and Barbuda",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/ag.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 11,
                "name" => "Argentina",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/ar.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 12,
                "name" => "Armenia",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/am.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 13,
                "name" => "Aruba",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/aw.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 14,
                "name" => "Australia",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/au.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 15,
                "name" => "Austria",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/at.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 16,
                "name" => "Azerbaijan",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/az.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 17,
                "name" => "Bahamas",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/bs.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 18,
                "name" => "Bahrain",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/bh.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 19,
                "name" => "Bangladesh",
                "timezone" => "UTC+06:00",
                "flag" => "https://flagcdn.com/w320/bd.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 20,
                "name" => "Barbados",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/bb.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 21,
                "name" => "Belarus",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/by.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 22,
                "name" => "Belgium",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/be.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 23,
                "name" => "Belize",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/bz.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 24,
                "name" => "Benin",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/bj.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 25,
                "name" => "Bermuda",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/bm.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 26,
                "name" => "Bhutan",
                "timezone" => "UTC+06:00",
                "flag" => "https://flagcdn.com/w320/bt.png",
                "createdAt" => "2022-12-06T10:23:44.541+00:00",
                "updatedAt" => "2022-12-06T10:23:44.541+00:00"
            ],
            [
                "id" => 27,
                "name" => "Bolivia (Plurinational State of)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/bo.png",
            ],
            [
                "id" => 28,
                "name" => "Bonaire, Sint Eustatius and Saba",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/bq.png",
            ],
            [
                "id" => 29,
                "name" => "Bosnia and Herzegovina",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ba.png",
            ],
            [
                "id" => 30,
                "name" => "Botswana",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/bw.png",
            ],
            [
                "id" => 31,
                "name" => "Bouvet Island",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/bv.png",
            ],
            [
                "id" => 32,
                "name" => "Brazil",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/br.png",
            ],
            [
                "id" => 33,
                "name" => "British Indian Ocean Territory",
                "timezone" => "UTC+06:00",
                "flag" => "https://flagcdn.com/w320/io.png",
            ],
            [
                "id" => 34,
                "name" => "United States Minor Outlying Islands",
                "timezone" => "UTC-11:00",
                "flag" => "https://flagcdn.com/w320/um.png",
            ],
            [
                "id" => 35,
                "name" => "Virgin Islands (British)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/vg.png",
            ],
            [
                "id" => 36,
                "name" => "Virgin Islands (U.S.)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/vi.png",
            ],
            [
                "id" => 37,
                "name" => "Brunei Darussalam",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/bn.png",
            ],
            [
                "id" => 38,
                "name" => "Bulgaria",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/bg.png",
            ],
            [
                "id" => 39,
                "name" => "Burkina Faso",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/bf.png",
            ],
            [
                "id" => 40,
                "name" => "Burundi",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/bi.png",
            ],
            [
                "id" => 41,
                "name" => "Cambodia",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/kh.png",
            ],
            [
                "id" => 42,
                "name" => "Cameroon",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/cm.png",
            ],
            [
                "id" => 43,
                "name" => "Canada",
                "timezone" => "UTC-08:00",
                "flag" => "https://flagcdn.com/w320/ca.png",
            ],
            [
                "id" => 44,
                "name" => "Cabo Verde",
                "timezone" => "UTC-01:00",
                "flag" => "https://flagcdn.com/w320/cv.png",
            ],
            [
                "id" => 45,
                "name" => "Cayman Islands",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/ky.png",
            ],
            [
                "id" => 46,
                "name" => "Central African Republic",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/cf.png",
            ],
            [
                "id" => 47,
                "name" => "Chad",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/td.png",
            ],
            [
                "id" => 48,
                "name" => "Chile",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/cl.png",
            ],
            [
                "id" => 49,
                "name" => "China",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/cn.png",
            ],
            [
                "id" => 50,
                "name" => "Christmas Island",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/cx.png",
            ],
            [
                "id" => 51,
                "name" => "Cocos (Keeling) Islands",
                "timezone" => "UTC+06:30",
                "flag" => "https://flagcdn.com/w320/cc.png",
            ],
            [
                "id" => 52,
                "name" => "Colombia",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/co.png",
            ],
            [
                "id" => 53,
                "name" => "Comoros",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/km.png",
            ],
            [
                "id" => 54,
                "name" => "Congo",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/cg.png",
            ],
            [
                "id" => 55,
                "name" => "Congo (Democratic Republic of the)",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/cd.png",
            ],
            [
                "id" => 56,
                "name" => "Cook Islands",
                "timezone" => "UTC-10:00",
                "flag" => "https://flagcdn.com/w320/ck.png",
            ],
            [
                "id" => 57,
                "name" => "Costa Rica",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/cr.png",
            ],
            [
                "id" => 58,
                "name" => "Croatia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/hr.png",
            ],
            [
                "id" => 59,
                "name" => "Cuba",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/cu.png",
            ],
            [
                "id" => 60,
                "name" => "Curaçao",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/cw.png",
            ],
            [
                "id" => 61,
                "name" => "Cyprus",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/cy.png",
            ],
            [
                "id" => 62,
                "name" => "Czech Republic",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/cz.png",
            ],
            [
                "id" => 63,
                "name" => "Denmark",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/dk.png",
            ],
            [
                "id" => 64,
                "name" => "Djibouti",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/dj.png",
            ],
            [
                "id" => 65,
                "name" => "Dominica",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/dm.png",
            ],
            [
                "id" => 66,
                "name" => "Dominican Republic",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/do.png",
            ],
            [
                "id" => 67,
                "name" => "Ecuador",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/ec.png",
            ],
            [
                "id" => 68,
                "name" => "Egypt",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/eg.png",
            ],
            [
                "id" => 69,
                "name" => "El Salvador",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/sv.png",
            ],
            [
                "id" => 70,
                "name" => "Equatorial Guinea",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/gq.png",
            ],
            [
                "id" => 71,
                "name" => "Eritrea",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/er.png",
            ],
            [
                "id" => 72,
                "name" => "Estonia",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ee.png",
            ],
            [
                "id" => 73,
                "name" => "Ethiopia",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/et.png",
            ],
            [
                "id" => 74,
                "name" => "Falkland Islands (Malvinas)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/fk.png",
            ],
            [
                "id" => 75,
                "name" => "Faroe Islands",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/fo.png",
            ],
            [
                "id" => 76,
                "name" => "Fiji",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/fj.png",
            ],
            [
                "id" => 77,
                "name" => "Finland",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/fi.png",
            ],
            [
                "id" => 78,
                "name" => "France",
                "timezone" => "UTC-10:00",
                "flag" => "https://flagcdn.com/w320/fr.png",
            ],
            [
                "id" => 79,
                "name" => "French Guiana",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/gf.png",
            ],
            [
                "id" => 80,
                "name" => "French Polynesia",
                "timezone" => "UTC-10:00",
                "flag" => "https://flagcdn.com/w320/pf.png",
            ],
            [
                "id" => 81,
                "name" => "French Southern Territories",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/tf.png",
            ],
            [
                "id" => 82,
                "name" => "Gabon",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ga.png",
            ],
            [
                "id" => 83,
                "name" => "Gambia",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/gm.png",
            ],
            [
                "id" => 84,
                "name" => "Georgia",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/ge.png",
            ],
            [
                "id" => 85,
                "name" => "Germany",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/de.png",
            ],
            [
                "id" => 86,
                "name" => "Ghana",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/gh.png",
            ],
            [
                "id" => 87,
                "name" => "Gibraltar",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/gi.png",
            ],
            [
                "id" => 88,
                "name" => "Greece",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/gr.png",
            ],
            [
                "id" => 89,
                "name" => "Greenland",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/gl.png",
            ],
            [
                "id" => 90,
                "name" => "Grenada",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/gd.png",
            ],
            [
                "id" => 91,
                "name" => "Guadeloupe",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/gp.png",
            ],
            [
                "id" => 92,
                "name" => "Guam",
                "timezone" => "UTC+10:00",
                "flag" => "https://flagcdn.com/w320/gu.png",
            ],
            [
                "id" => 93,
                "name" => "Guatemala",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/gt.png",
            ],
            [
                "id" => 94,
                "name" => "Guernsey",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/gg.png",
            ],
            [
                "id" => 95,
                "name" => "Guinea",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/gn.png",
            ],
            [
                "id" => 96,
                "name" => "Guinea-Bissau",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/gw.png",
            ],
            [
                "id" => 97,
                "name" => "Guyana",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/gy.png",
            ],
            [
                "id" => 98,
                "name" => "Haiti",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/ht.png",
            ],
            [
                "id" => 99,
                "name" => "Heard Island and McDonald Islands",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/hm.png",
            ],
            [
                "id" => 100,
                "name" => "Vatican City",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/va.png",
            ],
            [
                "id" => 101,
                "name" => "Honduras",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/hn.png",
            ],
            [
                "id" => 102,
                "name" => "Hungary",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/hu.png",
            ],
            [
                "id" => 103,
                "name" => "Hong Kong",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/hk.png",
            ],
            [
                "id" => 104,
                "name" => "Iceland",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/is.png",
            ],
            [
                "id" => 105,
                "name" => "India",
                "timezone" => "UTC+05:30",
                "flag" => "https://flagcdn.com/w320/in.png",
            ],
            [
                "id" => 106,
                "name" => "Indonesia",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/id.png",
            ],
            [
                "id" => 107,
                "name" => "Ivory Coast",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/ci.png",
            ],
            [
                "id" => 108,
                "name" => "Iran (Islamic Republic of)",
                "timezone" => "UTC+03:30",
                "flag" => "https://flagcdn.com/w320/ir.png",
            ],
            [
                "id" => 109,
                "name" => "Iraq",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/iq.png",
            ],
            [
                "id" => 110,
                "name" => "Ireland",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/ie.png",
            ],
            [
                "id" => 111,
                "name" => "Isle of Man",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/im.png",
            ],
            [
                "id" => 112,
                "name" => "Israel",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/il.png",
            ],
            [
                "id" => 113,
                "name" => "Italy",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/it.png",
            ],
            [
                "id" => 114,
                "name" => "Jamaica",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/jm.png",
            ],
            [
                "id" => 115,
                "name" => "Japan",
                "timezone" => "UTC+09:00",
                "flag" => "https://flagcdn.com/w320/jp.png",
            ],
            [
                "id" => 116,
                "name" => "Jersey",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/je.png",
            ],
            [
                "id" => 117,
                "name" => "Jordan",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/jo.png",
            ],
            [
                "id" => 118,
                "name" => "Kazakhstan",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/kz.png",
            ],
            [
                "id" => 119,
                "name" => "Kenya",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/ke.png",
            ],
            [
                "id" => 120,
                "name" => "Kiribati",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/ki.png",
            ],
            [
                "id" => 121,
                "name" => "Kuwait",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/kw.png",
            ],
            [
                "id" => 122,
                "name" => "Kyrgyzstan",
                "timezone" => "UTC+06:00",
                "flag" => "https://flagcdn.com/w320/kg.png",
            ],
            [
                "id" => 123,
                "name" => "Lao People's Democratic Republic",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/la.png",
            ],
            [
                "id" => 124,
                "name" => "Latvia",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/lv.png",
            ],
            [
                "id" => 125,
                "name" => "Lebanon",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/lb.png",
            ],
            [
                "id" => 126,
                "name" => "Lesotho",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ls.png",
            ],
            [
                "id" => 127,
                "name" => "Liberia",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/lr.png",
            ],
            [
                "id" => 128,
                "name" => "Libya",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ly.png",
            ],
            [
                "id" => 129,
                "name" => "Liechtenstein",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/li.png",
            ],
            [
                "id" => 130,
                "name" => "Lithuania",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/lt.png",
            ],
            [
                "id" => 131,
                "name" => "Luxembourg",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/lu.png",
            ],
            [
                "id" => 132,
                "name" => "Macao",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/mo.png",
            ],
            [
                "id" => 133,
                "name" => "North Macedonia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/mk.png",
            ],
            [
                "id" => 134,
                "name" => "Madagascar",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/mg.png",
            ],
            [
                "id" => 135,
                "name" => "Malawi",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/mw.png",
            ],
            [
                "id" => 136,
                "name" => "Malaysia",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/my.png",
            ],
            [
                "id" => 137,
                "name" => "Maldives",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/mv.png",
            ],
            [
                "id" => 138,
                "name" => "Mali",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/ml.png",
            ],
            [
                "id" => 139,
                "name" => "Malta",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/mt.png",
            ],
            [
                "id" => 140,
                "name" => "Marshall Islands",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/mh.png",
            ],
            [
                "id" => 141,
                "name" => "Martinique",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/mq.png",
            ],
            [
                "id" => 142,
                "name" => "Mauritania",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/mr.png",
            ],
            [
                "id" => 143,
                "name" => "Mauritius",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/mu.png",
            ],
            [
                "id" => 144,
                "name" => "Mayotte",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/yt.png",
            ],
            [
                "id" => 145,
                "name" => "Mexico",
                "timezone" => "UTC-08:00",
                "flag" => "https://flagcdn.com/w320/mx.png",
            ],
            [
                "id" => 146,
                "name" => "Micronesia (Federated States of)",
                "timezone" => "UTC+10:00",
                "flag" => "https://flagcdn.com/w320/fm.png",
            ],
            [
                "id" => 147,
                "name" => "Moldova (Republic of)",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/md.png",
            ],
            [
                "id" => 148,
                "name" => "Monaco",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/mc.png",
            ],
            [
                "id" => 149,
                "name" => "Mongolia",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/mn.png",
            ],
            [
                "id" => 150,
                "name" => "Montenegro",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/me.png",
            ],
            [
                "id" => 151,
                "name" => "Montserrat",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/ms.png",
            ],
            [
                "id" => 152,
                "name" => "Morocco",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/ma.png",
            ],
            [
                "id" => 153,
                "name" => "Mozambique",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/mz.png",
            ],
            [
                "id" => 154,
                "name" => "Myanmar",
                "timezone" => "UTC+06:30",
                "flag" => "https://flagcdn.com/w320/mm.png",
            ],
            [
                "id" => 155,
                "name" => "Namibia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/na.png",
            ],
            [
                "id" => 156,
                "name" => "Nauru",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/nr.png",
            ],
            [
                "id" => 157,
                "name" => "Nepal",
                "timezone" => "UTC+05:45",
                "flag" => "https://flagcdn.com/w320/np.png",
            ],
            [
                "id" => 158,
                "name" => "Netherlands",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/nl.png",
            ],
            [
                "id" => 159,
                "name" => "New Caledonia",
                "timezone" => "UTC+11:00",
                "flag" => "https://flagcdn.com/w320/nc.png",
            ],
            [
                "id" => 160,
                "name" => "New Zealand",
                "timezone" => "UTC-11:00",
                "flag" => "https://flagcdn.com/w320/nz.png",
            ],
            [
                "id" => 161,
                "name" => "Nicaragua",
                "timezone" => "UTC-06:00",
                "flag" => "https://flagcdn.com/w320/ni.png",
            ],
            [
                "id" => 162,
                "name" => "Niger",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ne.png",
            ],
            [
                "id" => 163,
                "name" => "Nigeria",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ng.png",
            ],
            [
                "id" => 164,
                "name" => "Niue",
                "timezone" => "UTC-11:00",
                "flag" => "https://flagcdn.com/w320/nu.png",
            ],
            [
                "id" => 165,
                "name" => "Norfolk Island",
                "timezone" => "UTC+11:30",
                "flag" => "https://flagcdn.com/w320/nf.png",
            ],
            [
                "id" => 166,
                "name" => "Korea (Democratic People's Republic of)",
                "timezone" => "UTC+09:00",
                "flag" => "https://flagcdn.com/w320/kp.png",
            ],
            [
                "id" => 167,
                "name" => "Northern Mariana Islands",
                "timezone" => "UTC+10:00",
                "flag" => "https://flagcdn.com/w320/mp.png",
            ],
            [
                "id" => 168,
                "name" => "Norway",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/no.png",
            ],
            [
                "id" => 169,
                "name" => "Oman",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/om.png",
            ],
            [
                "id" => 170,
                "name" => "Pakistan",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/pk.png",
            ],
            [
                "id" => 171,
                "name" => "Palau",
                "timezone" => "UTC+09:00",
                "flag" => "https://flagcdn.com/w320/pw.png",
            ],
            [
                "id" => 172,
                "name" => "Palestine, State of",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ps.png",
            ],
            [
                "id" => 173,
                "name" => "Panama",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/pa.png",
            ],
            [
                "id" => 174,
                "name" => "Papua New Guinea",
                "timezone" => "UTC+10:00",
                "flag" => "https://flagcdn.com/w320/pg.png",
            ],
            [
                "id" => 175,
                "name" => "Paraguay",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/py.png",
            ],
            [
                "id" => 176,
                "name" => "Peru",
                "timezone" => "UTC-05:00",
                "flag" => "https://flagcdn.com/w320/pe.png",
            ],
            [
                "id" => 177,
                "name" => "Philippines",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/ph.png",
            ],
            [
                "id" => 178,
                "name" => "Pitcairn",
                "timezone" => "UTC-08:00",
                "flag" => "https://flagcdn.com/w320/pn.png",
            ],
            [
                "id" => 179,
                "name" => "Poland",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/pl.png",
            ],
            [
                "id" => 180,
                "name" => "Portugal",
                "timezone" => "UTC-01:00",
                "flag" => "https://flagcdn.com/w320/pt.png",
            ],
            [
                "id" => 181,
                "name" => "Puerto Rico",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/pr.png",
            ],
            [
                "id" => 182,
                "name" => "Qatar",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/qa.png",
            ],
            [
                "id" => 183,
                "name" => "Republic of Kosovo",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/xk.png",
            ],
            [
                "id" => 184,
                "name" => "Réunion",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/re.png",
            ],
            [
                "id" => 185,
                "name" => "Romania",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ro.png",
            ],
            [
                "id" => 186,
                "name" => "Russian Federation",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/ru.png",
            ],
            [
                "id" => 187,
                "name" => "Rwanda",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/rw.png",
            ],
            [
                "id" => 188,
                "name" => "Saint Barthélemy",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/bl.png",
            ],
            [
                "id" => 189,
                "name" => "Saint Helena, Ascension and Tristan da Cunha",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/sh.png",
            ],
            [
                "id" => 190,
                "name" => "Saint Kitts and Nevis",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/kn.png",
            ],
            [
                "id" => 191,
                "name" => "Saint Lucia",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/lc.png",
            ],
            [
                "id" => 192,
                "name" => "Saint Martin (French part)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/mf.png",
            ],
            [
                "id" => 193,
                "name" => "Saint Pierre and Miquelon",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/pm.png",
            ],
            [
                "id" => 194,
                "name" => "Saint Vincent and the Grenadines",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/vc.png",
            ],
            [
                "id" => 195,
                "name" => "Samoa",
                "timezone" => "UTC+13:00",
                "flag" => "https://flagcdn.com/w320/ws.png",
            ],
            [
                "id" => 196,
                "name" => "San Marino",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/sm.png",
            ],
            [
                "id" => 197,
                "name" => "Sao Tome and Principe",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/st.png",
            ],
            [
                "id" => 198,
                "name" => "Saudi Arabia",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/sa.png",
            ],
            [
                "id" => 199,
                "name" => "Senegal",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/sn.png",
            ],
            [
                "id" => 200,
                "name" => "Serbia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/rs.png",
            ],
            [
                "id" => 201,
                "name" => "Seychelles",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/sc.png",
            ],
            [
                "id" => 202,
                "name" => "Sierra Leone",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/sl.png",
            ],
            [
                "id" => 203,
                "name" => "Singapore",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/sg.png",
            ],
            [
                "id" => 204,
                "name" => "Sint Maarten (Dutch part)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/sx.png",
            ],
            [
                "id" => 205,
                "name" => "Slovakia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/sk.png",
            ],
            [
                "id" => 206,
                "name" => "Slovenia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/si.png",
            ],
            [
                "id" => 207,
                "name" => "Solomon Islands",
                "timezone" => "UTC+11:00",
                "flag" => "https://flagcdn.com/w320/sb.png",
            ],
            [
                "id" => 208,
                "name" => "Somalia",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/so.png",
            ],
            [
                "id" => 209,
                "name" => "South Africa",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/za.png",
            ],
            [
                "id" => 210,
                "name" => "South Georgia and the South Sandwich Islands",
                "timezone" => "UTC-02:00",
                "flag" => "https://flagcdn.com/w320/gs.png",
            ],
            [
                "id" => 211,
                "name" => "Korea (Republic of)",
                "timezone" => "UTC+09:00",
                "flag" => "https://flagcdn.com/w320/kr.png",
            ],
            [
                "id" => 212,
                "name" => "Spain",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/es.png",
            ],
            [
                "id" => 213,
                "name" => "Sri Lanka",
                "timezone" => "UTC+05:30",
                "flag" => "https://flagcdn.com/w320/lk.png",
            ],
            [
                "id" => 214,
                "name" => "Sudan",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/sd.png",
            ],
            [
                "id" => 215,
                "name" => "South Sudan",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/ss.png",
            ],
            [
                "id" => 216,
                "name" => "Suriname",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/sr.png",
            ],
            [
                "id" => 217,
                "name" => "Svalbard and Jan Mayen",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/sj.png",
            ],
            [
                "id" => 218,
                "name" => "Swaziland",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/sz.png",
            ],
            [
                "id" => 219,
                "name" => "Sweden",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/se.png",
            ],
            [
                "id" => 220,
                "name" => "Switzerland",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/ch.png",
            ],
            [
                "id" => 221,
                "name" => "Syrian Arab Republic",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/sy.png",
            ],
            [
                "id" => 222,
                "name" => "Taiwan",
                "timezone" => "UTC+08:00",
                "flag" => "https://flagcdn.com/w320/tw.png",
            ],
            [
                "id" => 223,
                "name" => "Tajikistan",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/tj.png",
            ],
            [
                "id" => 224,
                "name" => "Tanzania, United Republic of",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/tz.png",
            ],
            [
                "id" => 225,
                "name" => "Thailand",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/th.png",
            ],
            [
                "id" => 226,
                "name" => "Timor-Leste",
                "timezone" => "UTC+09:00",
                "flag" => "https://flagcdn.com/w320/tl.png",
            ],
            [
                "id" => 227,
                "name" => "Togo",
                "timezone" => "UTC",
                "flag" => "https://flagcdn.com/w320/tg.png",
            ],
            [
                "id" => 228,
                "name" => "Tokelau",
                "timezone" => "UTC+13:00",
                "flag" => "https://flagcdn.com/w320/tk.png",
            ],
            [
                "id" => 229,
                "name" => "Tonga",
                "timezone" => "UTC+13:00",
                "flag" => "https://flagcdn.com/w320/to.png",
            ],
            [
                "id" => 230,
                "name" => "Trinidad and Tobago",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/tt.png",
            ],
            [
                "id" => 231,
                "name" => "Tunisia",
                "timezone" => "UTC+01:00",
                "flag" => "https://flagcdn.com/w320/tn.png",
            ],
            [
                "id" => 232,
                "name" => "Turkey",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/tr.png",
            ],
            [
                "id" => 233,
                "name" => "Turkmenistan",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/tm.png",
            ],
            [
                "id" => 234,
                "name" => "Turks and Caicos Islands",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/tc.png",
            ],
            [
                "id" => 235,
                "name" => "Tuvalu",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/tv.png",
            ],
            [
                "id" => 236,
                "name" => "Uganda",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/ug.png",
            ],
            [
                "id" => 237,
                "name" => "Ukraine",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/ua.png",
            ],
            [
                "id" => 238,
                "name" => "United Arab Emirates",
                "timezone" => "UTC+04:00",
                "flag" => "https://flagcdn.com/w320/ae.png",
            ],
            [
                "id" => 239,
                "name" => "United Kingdom of Great Britain and Northern Ireland",
                "timezone" => "UTC-08:00",
                "flag" => "https://flagcdn.com/w320/gb.png",
            ],
            [
                "id" => 240,
                "name" => "United States of America",
                "timezone" => "UTC-12:00",
                "flag" => "https://flagcdn.com/w320/us.png",
            ],
            [
                "id" => 241,
                "name" => "Uruguay",
                "timezone" => "UTC-03:00",
                "flag" => "https://flagcdn.com/w320/uy.png",
            ],
            [
                "id" => 242,
                "name" => "Uzbekistan",
                "timezone" => "UTC+05:00",
                "flag" => "https://flagcdn.com/w320/uz.png",
            ],
            [
                "id" => 243,
                "name" => "Vanuatu",
                "timezone" => "UTC+11:00",
                "flag" => "https://flagcdn.com/w320/vu.png",
            ],
            [
                "id" => 244,
                "name" => "Venezuela (Bolivarian Republic of)",
                "timezone" => "UTC-04:00",
                "flag" => "https://flagcdn.com/w320/ve.png",
            ],
            [
                "id" => 245,
                "name" => "Vietnam",
                "timezone" => "UTC+07:00",
                "flag" => "https://flagcdn.com/w320/vn.png",
            ],
            [
                "id" => 246,
                "name" => "Wallis and Futuna",
                "timezone" => "UTC+12:00",
                "flag" => "https://flagcdn.com/w320/wf.png",
            ],
            [
                "id" => 247,
                "name" => "Western Sahara",
                "timezone" => "UTC+00:00",
                "flag" => "https://flagcdn.com/w320/eh.png",
            ],
            [
                "id" => 248,
                "name" => "Yemen",
                "timezone" => "UTC+03:00",
                "flag" => "https://flagcdn.com/w320/ye.png",
            ],
            [
                "id" => 249,
                "name" => "Zambia",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/zm.png",
            ],
            [
                "id" => 250,
                "name" => "Zimbabwe",
                "timezone" => "UTC+02:00",
                "flag" => "https://flagcdn.com/w320/zw.png",
            ]
        ];


        foreach ($countrylist as $country) {
            Team::create([
                'name' => $country['name'],
                'is_country' => true,
                'flag_url' => $country['flag'],
            ]);
        }

    }
}
